### ISSUE TITLE
Ubuntu build broken

### ISSUE THREAD

**Issue by teverett** [cosmos-ssi/cosmos#61]
I believe the issue is due to uwyi.   It doesnt run on OS X.  I checked in code which uwyi is modifying.

**Comment by kurtmweber** [comment]
I noticed some of my pushes were failing on ubuntu, too.  In one case it was because I had forgot to #include <types.h> (it built on my system because it was already being included from another include), so iwyu was "helpfully" adding #include <stdint.h> to cover uint64_t, which of course is wrong in this case.  I fixed that, but it looks like there were other issues too.

But yeah, I'm using the same Makefile as you both are, and it's building on my (Slackware) Linux system and apparently OSX, so hmm.

**Comment by jschnurr** [comment]
I'll have a look.  <Stdint.h> is a common substitution provided by IWYU -
it's wrong but it really likes the system includes, and while I've been
able to coerce it into doing the right thing for all other cases stdint.h
has been stubborn.  You're correct that replacing with types.h resolves it.

**Comment by jschnurr** [comment]
I fixed the build.  `make clean; make header-fix` did the trick (in Ubuntu).

Keep in mind that IWYU is built on Make, so it only acts on changed files.  If you're running it locally, I find that `clean` is required first, because headers may change in files other than those you modified.

@teverett yes, I'll write some docs :)

I'll open another issue for the OS X problems; seems like more is broken there.
